/*******************************************************************************
 * Copyright (c) 2011, 2017 Eurotech and/or its affiliates and others
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *  
 * Contributors:
 *     Eurotech - initial API and implementation
 *******************************************************************************/
package org.eclipse.kapua.service.datastore;

import org.eclipse.kapua.KapuaException;
import org.eclipse.kapua.message.KapuaMessage;
import org.eclipse.kapua.model.id.KapuaId;
import org.eclipse.kapua.service.KapuaService;
import org.eclipse.kapua.service.config.KapuaConfigurableService;
import org.eclipse.kapua.service.datastore.model.DatastoreMessage;
import org.eclipse.kapua.service.datastore.model.MessageListResult;
import org.eclipse.kapua.service.datastore.model.StorableId;
import org.eclipse.kapua.service.datastore.model.query.StorableFetchStyle;
import org.eclipse.kapua.service.datastore.model.query.MessageQuery;

/**
 * Service responsible for storing and accessing telemetry data generated by devices.
 */
public interface MessageStoreService extends KapuaService,
                                     KapuaConfigurableService
{
    StorableId store(KapuaId scopeId, KapuaMessage<?,?> message)
        throws KapuaException;

    void delete(KapuaId scopeId, StorableId id)
        throws KapuaException;

    DatastoreMessage find(KapuaId scopeId, StorableId id, StorableFetchStyle fetchStyle)
        throws KapuaException;

    MessageListResult query(KapuaId scopeId, MessageQuery query)
        throws KapuaException;

    long count(KapuaId scopeId, MessageQuery query)
        throws KapuaException;

    void delete(KapuaId scopeId, MessageQuery query)
        throws KapuaException;
}
